"""Add ON DELETE CASCADE to comment.bug_id

Revision ID: 68f30f03ce1c
Revises: c53d723ea515
Create Date: 2025-11-19 16:38:05.774499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f30f03ce1c'
down_revision: Union[str, Sequence[str], None] = 'c53d723ea515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comment_bug_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'bug', ['bug_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_bug_id_fkey'), 'comment', 'bug', ['bug_id'], ['id'])
    # ### end Alembic commands ###
