"""Add comment model and relationships

Revision ID: c53d723ea515
Revises: a2eec33ea526
Create Date: 2025-11-06 20:07:58.495030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53d723ea515'
down_revision: Union[str, Sequence[str], None] = 'a2eec33ea526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bug_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bug.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_bug_id', 'comment', ['bug_id'], unique=False)
    op.create_index('idx_comment_created_by_id', 'comment', ['created_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comment_created_by_id', table_name='comment')
    op.drop_index('idx_comment_bug_id', table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
